//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Service
    {
        public int id_receipt { get; set; }
        public string service { get; set; }
    
        public virtual Receipt Receipt { get; set; }
        public virtual Receipt Receipt1 { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
